### ISSUE TITLE
Some audio with very little speech in them fails ("Erreur : une erreur s'est déclenchée pendant le traitement de l'audio" / " Error : an error has occured during processing the audio"

### ISSUE THREAD

**Issue by Jeronymous** [linto-ai/platform-conversation-manager#68]
Importing the enclosed audio fails.

I didn't use any additional service, just asked for transcription
```
Speaker identification : disabled
Punctuation : disabled
Normalization : enabled
```

[018a_EARZ_057.zip](https://github.com/linto-ai/platform-conversation-manager/files/10709031/018a_EARZ_057.zip)

**Comment by damienlaine** [comment]
Here's the complete trace that lead to the crash :

INFO Input file has been split into 1 subfiles 15:37:05,INFO Transcription task complete 15:37:05,INFO Task complete, post processing ... 15:37:05,ERROR Task transcription_task[3aad628d-865e-48af-9676-b6abbd55bcd7] raised unexpected: Exception('Failed to process result') Traceback (most recent call last): File "/usr/src/app/transcriptionservice/server/mongodb/db_client.py", line 27, in inner_func res = func(*args, **kwargs) File "/usr/src/app/transcriptionservice/server/mongodb/db_client.py", line 108, in push_result "result": result.final_result(), File "/usr/src/app/transcriptionservice/transcription/transcription_result.py", line 186, in final_result result["segments"] = [s.json for s in self.segments] File "/usr/src/app/transcriptionservice/transcription/transcription_result.py", line 186, in result["segments"] = [s.json for s in self.segments] File "/usr/src/app/transcriptionservice/transcription/transcription_result.py", line 57, in json "start": self.start, File "/usr/src/app/transcriptionservice/transcription/transcription_result.py", line 43, in start return min([w.start for w in self.words]) ValueError: min() arg is an empty sequence During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/app/transcriptionservice/transcription/transcription_task.py", line 244, in transcription_task result_id = db_client.push_result( File "/usr/src/app/transcriptionservice/server/mongodb/db_client.py", line 31, in inner_func raise Exception("Database error: {}".format(e)) Exception: Database error: min() arg is an empty sequence During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task R = retval = fun(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__ return self.run(*args, **kwargs) File "/usr/src/app/transcriptionservice/transcription/transcription_task.py", line 253, in transcription_task raise Exception("Failed to process result") Exception: Failed to process result

**Comment by damienlaine** [comment]
As the transcription service might produce an empty transcription, it would be better to halt subsequent tasks, such as diarization, and return a relevant error message, instead of publishing empty resources. This would help prevent further implementation errors on front-ends that might rely on these resources.
